name: Autobuilder release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, test]
    container: cruizba/ubuntu-dind:focal-25.0.3
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Generate version
        id: version
        run: echo "version=$(date +'%Y.%m.%d').$(echo "${{ github.sha }}" | cut -c 1-7)" >> $GITHUB_OUTPUT

      - name: Build autobuilder jar
        run: ./gradlew :projectAutoBuilderJar -PanalyzerVersion=${{ steps.version.outputs.version }}
        env:
          SEQRA_GITHUB_ACTOR: ${{ secrets.SEQRA_GITHUB_ACTOR }}
          SEQRA_GITHUB_TOKEN: ${{ secrets.SEQRA_GITHUB_TOKEN }}

      - name: Build autobuilder docker image
        run: ./gradlew :buildProjectAutoBuilderDocker -PanalyzerVersion=${{ steps.version.outputs.version }}
        env:
          SEQRA_GITHUB_ACTOR: ${{ secrets.SEQRA_GITHUB_ACTOR }}
          SEQRA_GITHUB_TOKEN: ${{ secrets.SEQRA_GITHUB_TOKEN }}

      - name: Create image names
        run: echo "AUTOBUILDER_IMAGE=ghcr.io/${{ github.repository_owner }}/seqra-jvm-autobuilder/sast-autobuilder:${{ steps.version.outputs.version }}" >> $GITHUB_ENV

      - name: Tag images
        run: docker tag autobuilder-private:${{ steps.version.outputs.version }} ${{ env.AUTOBUILDER_IMAGE }}

      # Run autobuilder on OWASP
      - name: Checkout owasp
        uses: actions/checkout@v4
        with:
          repository: 'OWASP-Benchmark/BenchmarkJava'
          path: ./test-dir/OWASP

      - name: Build owasp
        run: |
          docker run -i -a stdout -a stderr --rm \
          -v ${{ github.workspace }}:/data \
          ${{ env.AUTOBUILDER_IMAGE }} \
          --project-root-dir /data/test-dir/OWASP \
          --build portable \
          --result-dir /data/test-dir/BenchmarkJava-portable-build \
          --logs-file /data/test-dir/autobuild.log \
          --verbosity debug

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        run: docker push ${{ env.AUTOBUILDER_IMAGE }}

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          prerelease: true
          files: build/libs/seqra-project-auto-builder.jar
          make_latests: false
